### ISSUE TITLE
Markdown text editor

### ISSUE THREAD

**Issue by dmcalli2** [jennybc/happy-git-with-r#81]
Very interesting and appealing ideas about using markdown to create easy web-pages in Github. For larger documents (eg a statistical analysis plan), should the book make some recommendations such as "For larger documents, you can write a first draft in a word processor such as word, then to enjoy the benefits of Github, use pandoc to convert it to github-flavoured markdown. Alternatively, if you prefer to draft it entirely in markdown, there are a number of markdown editors with features like syntax highlighting and previewing (link to list of recommended editors)"

**Comment by jennybc** [comment]
The book is pretty focused on combining **R** with Git and GitHub, hence the emphasis on Rmd-based workflows. But I certainly wouldn't object to a well-placed paragraph somewhere about "what if you've just got Markdown?", if you'd like to make such a PR.

I am reluctant to include recommendation lists for things I don't use personally, because they are very subject to link rot. I revisit the "Git client/GUI" topic often enough that I am willing to include. However, I am not keen to maintain a list of markdown editors and would rather point to a highly-stable resource (does GitHub maintain such a page?).

Agree you could mention pandoc as a way to convert very disparate things to GFM. If you've got markdown that's not GFM, I'm pretty sure you can just change extension to `.Rmd`, request GFM in the yaml, and use `rmarkdown::render()`. This is, of course, calling pandoc under the hood, but is nice to know about for someone who has no desire to personally install and call pandoc. You'd have to check my hunch, obviously. You can use `.Rmd` & RStudio for plain ol' markdown editing, even if there aren't any executable chunks. Yes, I'm clearly assuming the audience has a lot of R in their life.
